# Site settings
title: yosulog
email: "woodstock830 {at} gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  Webテクノロジー、プログラミング、ソフトウェア開発についてのブログです。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yosu.github.io" # the base hostname & protocol for your site
twitter_username: yosu
github_username:  yosu

timezone: "Asia/Tokyo"
permalink: "/:year/:month/:day/:title/"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  coderay_line_numbers: nil

# Exclude
exclude: [
  Gruntfile.js,
  node_modules,
  package.json
]
